### ISSUE TITLE
Doesn't work with latest Alchema version

### ISSUE THREAD

**Issue by Hellcode48** [2008Choco/AlchemicalArrows#15]
Basically just needs an update for latest Alchema version plus 1.18

java.lang.IncompatibleClassChangeError: Method 'wtf.choco.alchema.crafting.CauldronRecipe$Builder wtf.choco.alchema.crafting.CauldronRecipe.builder(org.bukkit.NamespacedKey, org.bukkit.inventory.ItemStack)' must be InterfaceMethodref constant
at wtf.choco.arrows.integration.alchema.PluginIntegrationAlchema.addRecipe(PluginIntegrationAlchema.java:69) ~[AlchemicalArrows-3.3.3.jar:?]
at wtf.choco.arrows.AlchemicalArrows.createAndRegisterArrow(AlchemicalArrows.java:302) ~[AlchemicalArrows-3.3.3.jar:?]
at wtf.choco.arrows.AlchemicalArrows.onEnable(AlchemicalArrows.java:129) ~[AlchemicalArrows-3.3.3.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.18.1.jar:git-Paper-82]
at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.18.1.jar:git-Paper-82]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.1.jar:git-Paper-82]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-82]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-82]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-82]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-82]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by 2008Choco** [comment]
Right. Fault on my part. I even had a build prepared to be released for AlchemicalArrows and it slipped my mind. I'll publish a release tomorrow to support the newest Alchema version.

**Comment by Hellcode48** [comment]
Hope you had a happy new year and Christmas! Just reminding you to publish that build when you get a chance, but there's no rush on my end
